"use client";

import { useState } from "react";
import { Bell, CheckCheck, Menu, Search } from "lucide-react";

const notifications = [
  { title: "Route 1 is ready", detail: "Driver and bus assignment are confirmed.", time: "Just now" },
  { title: "Student transport updated", detail: "A student was assigned to a route.", time: "18 min ago" },
  { title: "Fleet check due", detail: "NEXO Bus 08 needs a maintenance review.", time: "Today" },
];

export function Header({ title, onMenuOpen }: { title: string; onMenuOpen: () => void }) {
  const [notificationsOpen, setNotificationsOpen] = useState(false); const [unread, setUnread] = useState(true);
  return <header className="sticky top-0 z-20 flex h-20 items-center justify-between border-b border-slate-200 bg-slate-50/90 px-5 backdrop-blur sm:px-8"><div className="flex items-center gap-3"><button onClick={onMenuOpen} aria-label="Open navigation" className="rounded-lg p-2 text-slate-600 hover:bg-white lg:hidden"><Menu size={22} /></button><h1 className="text-xl font-semibold text-slate-950 sm:text-2xl">{title}</h1></div><div className="flex items-center gap-2 sm:gap-4"><label className="relative hidden md:block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} aria-hidden="true" /><input aria-label="Search" placeholder="Search anything..." className="h-10 w-56 rounded-lg border border-slate-200 bg-white pl-10 pr-3 text-sm outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100" /></label><div className="relative"><button onClick={() => setNotificationsOpen(open => !open)} aria-label="Notifications" aria-expanded={notificationsOpen} className="relative rounded-lg p-2.5 text-slate-600 hover:bg-white focus:outline-none focus:ring-2 focus:ring-teal-500"><Bell size={20} />{unread && <span className="absolute right-2 top-2 size-2 rounded-full bg-teal-500" />}</button>{notificationsOpen && <section aria-label="Notification center" className="absolute right-0 top-12 w-80 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div><h2 className="font-semibold text-slate-900">Notifications</h2><p className="text-xs text-slate-500">Operational updates</p></div><button onClick={() => setUnread(false)} className="inline-flex items-center gap-1 text-xs font-semibold text-teal-700 hover:text-teal-900"><CheckCheck size={15}/>Mark all read</button></div><div>{notifications.map(notification => <article key={notification.title} className="border-b border-slate-100 px-4 py-3 last:border-0"><p className="text-sm font-semibold text-slate-800">{notification.title}</p><p className="mt-1 text-sm text-slate-500">{notification.detail}</p><p className="mt-1.5 text-xs font-medium text-teal-700">{notification.time}</p></article>)}</div></section>}</div><div className="hidden items-center gap-3 border-l border-slate-200 pl-4 sm:flex"><span className="flex size-10 items-center justify-center rounded-full bg-teal-100 font-semibold text-teal-700">NA</span><div className="text-sm"><p className="font-medium text-slate-800">NEXO Administrator</p><p className="text-slate-500">Administrator</p></div></div></div></header>;
}
