"use client";
import { useState } from "react";
import { MapPin, Pencil, Plus } from "lucide-react";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Field, inputClass, Modal, StatusBadge, Toast } from "@/components/ui/ManagementUi";
import { useNexoData } from "@/components/providers/NexoDataProvider";
import type { Route } from "@/types/entities";

export function RouteLocationsManager() {
  const { routes, setRoutes, schools, buses, drivers, students } = useNexoData();
  const [editing, setEditing] = useState<Route | null>(null); const [toast, setToast] = useState("");
  const notify = (message: string) => { setToast(message); setTimeout(() => setToast(""), 2500); };
  const save = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const updated = { ...editing!, pickupLocation: String(form.get("pickup")), dropoffLocation: String(form.get("dropoff")) }; setRoutes(items => items.map(item => item.id === updated.id ? updated : item)); setEditing(null); notify("Pickup and drop-off locations updated."); };
  return <DashboardLayout title="Routes"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">Routes</h2><p className="mt-1 text-slate-600">View and manage pickup and drop-off locations for every school route.</p></div><button onClick={() => notify("Choose a route below to add its locations.")} className="inline-flex items-center gap-2 rounded-lg bg-teal-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={18}/>Add locations</button></div><div className="mt-7 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-4"><table className="min-w-[980px] w-full text-left text-sm"><thead><tr>{["Route","School","Pickup location","Drop-off location","Bus","Driver","Students","Status","Action"].map(title => <th key={title} className="border-b px-3 py-3 font-medium text-slate-500">{title}</th>)}</tr></thead><tbody>{routes.map(route => <tr key={route.id} className="border-b border-slate-100"><td className="px-3 py-4 font-semibold">{route.name}</td><td className="px-3 py-4">{schools.find(s => s.id === route.schoolId)?.name ?? "—"}</td><td className="px-3 py-4"><Location value={route.pickupLocation}/></td><td className="px-3 py-4"><Location value={route.dropoffLocation}/></td><td className="px-3 py-4">{buses.find(b => b.id === route.busId)?.name ?? "—"}</td><td className="px-3 py-4">{drivers.find(d => d.id === route.driverId)?.name ?? "—"}</td><td className="px-3 py-4">{students.filter(student => student.routeId === route.id).length}</td><td className="px-3 py-4"><StatusBadge status={route.status}/></td><td className="px-3 py-4"><button aria-label={`Edit locations for ${route.name}`} onClick={() => setEditing(route)} className="inline-flex items-center gap-1 rounded-lg px-2 py-1.5 text-teal-700 hover:bg-teal-50"><Pencil size={16}/>Edit</button></td></tr>)}</tbody></table></div>{editing && <Modal title={`Locations — ${editing.name}`} onClose={() => setEditing(null)}><form onSubmit={save} className="space-y-4"><p className="text-sm text-slate-600">Set the passenger collection point and school or final destination for this route.</p><Field label="Pickup location *"><input required name="pickup" defaultValue={editing.pickupLocation ?? ""} placeholder="e.g. Kacyiru Taxi Park" className={inputClass}/></Field><Field label="Drop-off location *"><input required name="dropoff" defaultValue={editing.dropoffLocation ?? ""} placeholder="e.g. Kigali International Academy" className={inputClass}/></Field><div className="flex justify-end gap-3"><button type="button" onClick={() => setEditing(null)} className="rounded-lg px-4 py-2 text-sm">Cancel</button><button className="rounded-lg bg-teal-600 px-4 py-2 text-sm font-semibold text-white">Save locations</button></div></form></Modal>}{toast && <Toast message={toast}/>}</DashboardLayout>;
}
function Location({ value }: { value?: string }) { return <span className="inline-flex items-center gap-1.5 text-slate-700"><MapPin size={15} className="text-teal-600"/>{value || "Not set"}</span>; }
